language: ruby
cache: bundler

rvm:
  - "2.1.2"
  - "2.1.1"
  - "2.1.0"
  - "2.0.0"
  - "rbx-2"
  - "ruby-head"
  - "jruby-head"

script: 'bundle exec rake spec'

branches:
  only:
    - master

notifications:
  email:
    - ericdejonckheere@gmail.com
